STATUS_DRAFT = 'DRAFT'
STATUS_RELEASE = 'RELEASE'

MARGINALITY_UNSPECIFIED = 'Unspecified'
MARGINALITY_NOT_APPLICABLE = 'Not Applicable'
MARGINALITY_RECOMMEDED = 'Recommended'
MARGINALITY_MINIMAL = 'Minimum'
MARGINALITY_OPTIONAL = 'Optional'

CARDINALITY_MANY = 'MANY'
CARDINALITY_ONE = 'ONE'
